### ISSUE TITLE
Connecting to EXT_GO database

### ISSUE THREAD

**Issue by coffeecer** [eurostat/PowerBI-connector#1]
HI, 

Great connector!
Was trying to use it for International trade in goods database, but diddn't succeed to build a quiry for following dataset:

> EU trade since 1999 by HS2,4,6 and CN8 - daily updated (DS-575274)

Neither "DS-575274" nor "EXT_GO_DETAIL" looks to be a valid Dataset codes. 

Please advise what code should be used in order to connect to the database "EU trade since 1999 by HS2,4,6 and CN8 - daily updated (DS-575274)"
Thank you!

**Comment by oloski** [comment]
Hi Yury

I've found out that international trade data is not supported by
WebServices  (
https://ec.europa.eu/eurostat/web/json-and-unicode-web-services/data-scope-and-query-size
)
You can try to use bulk download.

Best

Aleksander

czw., 26 gru 2019 o 16:02 Yury <notifications@github.com> napisał(a):

**Comment by oloski** [comment]
...
