### ISSUE TITLE
Cant find the custom connector in PowerBi

### ISSUE THREAD

**Issue by gerresson12** [eurostat/PowerBI-connector#2]
Hi,
I followed the steps in the installation. However, didt have a custom connectors folder in my powerbi desktop (from appstore) directory so i created one.

Also changed the security settings in PowerBi.

But the custom connector is not showing up, not sure why?

**Comment by oloski** [comment]
HI,

Do you have Eurostat API.mez file in 'Documents\(Microsoft) Power BI
Desktop\Custom Connectors' folder?
It is quite well hidden in "Get Data" window - under OLE DB

[image: image.png]

Best
Aleksander


wt., 9 cze 2020 o 08:35 gerresson12 <notifications@github.com> napisał(a):

**Comment by gerresson12** [comment]
OK thanks it worked
