### ISSUE TITLE
"Field already exists" error in _Relations table

### ISSUE THREAD

**Issue by BFleuren** [eurostat/PowerBI-connector#3]
When importing  a dataset, the connector shows all tables and pulls them in, with the exception of the _Relations table, because I get an error message "The field 'index_isco08' already exists in the record.
[EUROSTAT.zip](https://github.com/eurostat/PowerBI-connector/files/6163532/EUROSTAT.zip)

![The field already exists](https://user-images.githubusercontent.com/80893008/111616752-8d6cab80-87e2-11eb-83c9-7c355a6a8347.jpg)
![Navigator](https://user-images.githubusercontent.com/80893008/111616764-92315f80-87e2-11eb-8b39-2d391a76c3e3.jpg)

**Comment by oloski** [comment]
HI,

Please remove _Eurostat API.mez_ file from ..._Documents\Power BI Desktop\Custom Connectors_ folder.
Reopen PowerBi and make sure that Eurostat connector has disappeared from the list.
Download _Eurostat API.pqx_ to ..._Documents\Power BI Desktop\Custom Connectors_ folder and try get data again.

I've checked the new version with this connection string: http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/educ_uoe_enrp01?precision=1&sex=F&sex=M&sex=T&unit=NR&isced11=ED0&isced11=ED02&worktime=FT&sector=PRIV

**Comment by BFleuren** [comment]
It works, thanks a lot!
